@startuml

title 九十九の源計算機 クラス図

class NolTsukumoApplication

class NolTsukumoModelObserverInterface {
  +onUpdateExpOfCurrentLevel(exp : number, max : number)
  +onUpdateToLevel(toLevel : number)
  +onUpdateToLevelMin(toLevelMin : number)
  +onUpdateNecessaryTsukumo(exp : number, source : number)
}
class NolTsukumoModel {
  +setCurrentLevel(level : number)
  +setCurrentExp(exp : number)
  +setCurrentNumOfActivatedTsukumo(numActivatedTsukumo : number)
  +setToLevel(expectedLevel : number)
  +setGain(gain : number)
  +registerObserver(observer : NolTsukumoModelObserverInterface)
}
NolTsukumoModel o-- NolTsukumoModelObserverInterface

class NolTsukumoView {
}
NolTsukumoModelObserverInterface <|.. NolTsukumoView
NolTsukumoView --> NolTsukumoModel

class NolTsukumoController {
  +update()
}
NolTsukumoModelObserverInterface <|.. NolTsukumoController
NolTsukumoController --> NolTsukumoModel

NolTsukumoApplication o-- NolTsukumoModel
NolTsukumoApplication o-- NolTsukumoView
NolTsukumoApplication o-- NolTsukumoController


@enduml
