@startuml

title 現在のレベル入力時のシーケンス図

actor ユーザー as user
participant HTML
participant NolTsukumoController
participant NolTsukumoView
participant NolTsukumoModel

user -> HTML++ : input event to current level
                  HTML -> NolTsukumoController++ : updateCurrentLevel(level)
                    NolTsukumoController -> NolTsukumoModel++ : setCurrentLevel(level)
                      NolTsukumoModel -> NolTsukumoModel++ : currentStatus.level = level
                      return
                      NolTsukumoModel -> NolTsukumoView++ : onUpdateCurrentLevel(level)
                              NolTsukumoView -> HTML++ : Update currentLevel
                              return
                      return
                      NolTsukumoModel -> NolTsukumoView++ : onUpdateExpToNextLevel(0)
                        NolTsukumoView -> HTML++ : Update exp to next level
                        return
                      return
                      NolTsukumoModel -> NolTsukumoModel++ : max = getExpToNextLevel(level) - 1
                      return
                      NolTsukumoModel -> NolTsukumoController++ : onUpdateMaxExpToNextLevel(maxExp)
                        NolTsukumoController -> HTML++ : Update max exp to next level
                        return
                      return
                      opt currentStatus.level >= this.toLevelMin
                        NolTsukumoModel -> NolTsukumoModel++ : this.toLevelMin = currentStatus.level + 1
                        return
                        NolTsukumoModel -> NolTsukumoController++ : onUpdateToLevelMin(this.toLevelMin)
                          NolTsukumoController -> HTML++ : Update min of toLevel
                          return        
                        return
                        opt toLevel < toLevelMin
                          NolTsukumoModel -> NolTsukumoModel++ : toLevel = toLevelMin
                          return
                          NolTsukumoModel -> NolTsukumoController++ : onUpdateToLevel(toLevel)
                            NolTsukumoController -> HTML++ : Update current toLevel
                            return        
                          return
                        end
                      end
                      NolTsukumoModel -> NolTsukumoModel++ : notifyNecessaryTsukumo()
                        ref over NolTsukumoModel, NolTsukumoView, HTML
                          Notify necessary Tsukumo source and exp, and update view.
                      end ref
                      return
                    return
                  return    
return

@enduml
