name: HTML5 Validator

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Validate HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
