name: lint

on:
  pull_request:

jobs:
  TypeScript:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install linters
        run: npm install

      - name: tslint
        run: make -j tslint

  CSS:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install linters
        run: npm install

      - name: stylelint
        run: make -j stylelint
